"""Generated by tools/build_world.py: shared world facts for the hub. Do not edit."""
META = {
 "lockable": [
  "hall:meet-a",
  "hall:meet-b"
 ],
 "maps": {
  "cafe": {
   "h": 11,
   "name": "Caf\u00e9",
   "w": 16
  },
  "chess": {
   "h": 11,
   "name": "Chess Club",
   "w": 16
  },
  "cinema": {
   "h": 12,
   "name": "Cinema",
   "w": 18
  },
  "den": {
   "h": 11,
   "name": "Game Den",
   "w": 16
  },
  "hall": {
   "h": 18,
   "name": "Town Hall",
   "w": 30
  },
  "town": {
   "h": 71,
   "name": "Mobius Town",
   "w": 64
  }
 },
 "pitch": {
  "map": "town",
  "rect": [
   20,
   53,
   24,
   14
  ]
 },
 "rooms": {
  "cafe": [
   "cafe"
  ],
  "chess": [
   "chess"
  ],
  "cinema": [
   "cinema"
  ],
  "den": [
   "den"
  ],
  "hall": [
   "lobby",
   "meet-a",
   "meet-b",
   "auditorium"
  ],
  "town": [
   "town"
  ]
 },
 "screens": [
  "tv"
 ],
 "stages": {
  "hall:auditorium": [
   [
    23,
    4
   ],
   [
    24,
    4
   ],
   [
    25,
    4
   ],
   [
    23,
    5
   ],
   [
    24,
    5
   ],
   [
    25,
    5
   ]
  ]
 },
 "tables": {
  "c4-1": {
   "kind": "connect4",
   "map": "den",
   "seats": [
    "r",
    "y"
   ]
  },
  "c4-2": {
   "kind": "connect4",
   "map": "den",
   "seats": [
    "r",
    "y"
   ]
  },
  "chess-1": {
   "kind": "chess",
   "map": "chess",
   "seats": [
    "w",
    "b"
   ]
  },
  "chess-2": {
   "kind": "chess",
   "map": "chess",
   "seats": [
    "w",
    "b"
   ]
  }
 }
}
